default_language_version:
    python: python3.10
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: debug-statements
-   repo: https://github.com/asottile/reorder_python_imports
    rev: v3.10.0
    hooks:
    -   id: reorder-python-imports
        args:
            - --application-directories=.:corrosion:erosion
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.7
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: 'v17.0.2'
    hooks:
    -   id: clang-format
        name: clang-format
        entry: clang-format -i
        files: ^(.*.cpp|.*.hpp)$
        language: system
